name: nasooh
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  lottie: ^2.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  responsive_framework: ^0.2.0
#  intl:
  flutter_spinkit: ^5.1.0
  intl_phone_field: ^3.1.0
  password_text_field: ^1.1.0
  flutter_svg: ^2.0.2
  dropdown_textfield: ^1.0.7
  flutter_native_splash: ^2.2.17
  badges: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  pinput: ^2.2.21
  image_picker: ^0.8.7
  dotted_border: ^2.0.0+3
  flutter_countdown_timer: ^4.1.0
  photo_view: ^0.14.0
  dotted_line: ^3.1.0
  get: ^4.6.5
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  firebase_core: ^2.15.1
  flutter_launcher_icons: ^0.13.1
  audioplayers:
  file_picker: ^5.2.4
  url_launcher:
  record: ^5.0.1
  permission_handler:
  flutter_linkify: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/PNG/logo.png"

flutter_native_splash:
  # color: "#0085A5"
  image: assets/images/PNG/NasohSplash.png
  background_image: assets/images/PNG/SplashScreenBackGround.png
  android: true
  ios: true
  android_12:
    color: "#0085A5"
    image: assets/images/PNG/NasohSplash.png
    background_image: assets/images/PNG/SplashScreenBackGround.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/SVGs/
    - assets/images/Jsons/
    - assets/images/PNG/
    - assets/language/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
